# Generated by Django 3.1.2 on 2022-01-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('startRecur', models.DateTimeField(blank=True, null=True)),
                ('endRecur', models.DateTimeField(blank=True, null=True)),
                ('daysOfWeek', models.JSONField(blank=True, null=True)),
                ('groupId', models.CharField(blank=True, max_length=50)),
                ('allDay', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3E80BD', max_length=7)),
                ('desc', models.TextField(blank=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='creator')),
            ],
        ),
    ]
