# Generated by Django 3.1.2 on 2020-10-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(db_index=True)),
                ('endDate', models.DateTimeField(db_index=True)),
                ('allDay', models.BooleanField()),
                ('rRule', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('end_recurring_period', models.DateTimeField(blank=True, db_index=True, help_text='This date is ignored for one time only events.', null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
