# Generated by Django 3.1.2 on 2020-10-17 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrakCalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_recurring_period',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rRule',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#3E80BD', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='daysOfWeek',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=7),
        ),
        migrations.AddField(
            model_name='event',
            name='endRecur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='groupId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='startRecur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
    ]
