# Generated by Django 3.1.2 on 2020-10-17 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrakCalendar', '0002_auto_20201017_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='daysOfWeek',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=7),
        ),
    ]
