# Generated by Django 3.1.2 on 2020-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrakCalendar', '0003_auto_20201017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='daysOfWeek',
            field=models.JSONField(null=True),
        ),
    ]
