# Generated by Django 3.1.2 on 2020-10-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrakCalendar', '0004_auto_20201017_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='startTime',
        ),
    ]
